env:
  browser: true
  node: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: 2021
  sourceType: module
rules: {
  "semi": ["error", "never"],
  "quotes": ["error", "single"]
}
